### ISSUE TITLE
FastAPI implementation throwing missing segment

### ISSUE THREAD

**Issue by sean-a-grant-old** [garyd203/xraysink#88] opened 2022-05-19 01:28 UTC
Hi, I am trying to utilize this library to implement X-Ray into my FastAPI api. 

I have the following code:
```
    xray_recorder.configure(context_missing="LOG_ERROR")
    xray_recorder.configure(service="API DEV")
    xray_recorder.configure(plugins=("ECSPlugin",))
    xray_patch_all()
    app.add_middleware(BaseHTTPMiddleware, dispatch=xray_middleware)
```

But on each request I send, I see the daemon only receives 1 segment. Usually with a response time of 0.04ms, which definitely isn't the case. I see that this segment is sent before the response is even sent to the client.

Along with this, the following is logged in my application:
`cannot find the current segment/subsegment, please make sure you have a segment open`

Is there a working example of this working with FastAPI? Am I missing something here? Thanks!

**Comment by sean-a-grant** [comment] 2022-05-19 21:21
@garyd203 Hi Gary, sorry to bug, but is this an old implementation? Need to know if I'm wasting my time trying to implement this solution.

**Comment by garyd203** [comment] 2022-05-20 04:29
Hi @sean-a-grant, yes other people are using `xraysink` to instrument FastAPI servers with X-Ray, and it is actively maintained (on a volunteer basis, like many other software libraries).

The upstream `aws_xray_sdk` library can be a bit tricky to configure correctly. I don't have a working example I can share at the moment (most people's usage of X-Ray tends to be proprietary), but happy to work through your example with you and see if we can reproduce and/or solve the problem.

A few analysis questions to get us started:

* What versions of everything do you have (`fastapi`, `xraysink`, `aws_xray_sdk`)?
* What other xray configuration or set up do you do in your code (apart from what's shown above)? I would normally expect to see a `context=AsyncContext()` of some sort.
* Do you have any of the `AWS_XRAY_` environment variables set?
* What other app configuration do you do? Is your `app` a vanilla `FastAPI` object, or have you customised it? Do you have any other middleware - what is it, and what order is it added in?
* Does your code explicitly start any segments/subsegments (eg. using `xray_recorder.in_segment_async`)?
* Are you using any other X-Ray libraries, such as the Lambda powertools?

Some things you can do yourself to troubleshoot:
* Set `context_missing="RUNTIME_ERROR"` for non-production, so that you get an exception to tell you when and where something breaks.
* If the above doesn't produce a useful stack trace, run your code in a debugger (I find it easy to do this inside a unit test), slap a breakpoint on the place in the `aws_xray_sdk` code where that error message appears, and see what you can learn from the call stack
* The internals of `aws_xray_sdk` can be confusing, but I've got some experience in that codebase so happy to help interpret any state or tracebacks you find if you post them here

**Comment by sean-a-grant** [comment] 2022-05-20 07:16
Hi @garyd203, thanks for writing back so quick. 

I wrote a clean version to reproduce the issue. My expectation is I would be able to see the individual calls and their time taken. I was not able to reproduce the traces being significantly shorter than the actual response, however.

**Versions:**
```
fastapi: 0.67.0
xraysink: 1.5.2
aws_xray_sdk: 2.9.0
```

**Implementation:**
```
...
from aws_xray_sdk.core import xray_recorder
from aws_xray_sdk.core import patch_all as xray_patch_all, patch as xray_patch
from xraysink.context import AsyncContext
from starlette.middleware.base import BaseHTTPMiddleware

app = FastAPI(title="API", openapi_url="/api/openapi.json", docs_url="/")

xray_recorder.configure(context_missing="LOG_ERROR")
xray_recorder.configure(service="API DEV clean")
xray_recorder.configure(service="API DEV clean", context=AsyncContext())
patch_all()

app.add_middleware(BaseHTTPMiddleware, dispatch=xray_middleware)
...

def more_work():
    sleep(1)

def do_work():
    more_work()
    sleep(0.5)
    return 1

@router.get('/test')
def test():
    engine.execute('SELECT pg_sleep(1);')
    result = do_work()
    return result
```

**Example response:**
```
 content-length: 1 
 content-type: application/json 
 date: Fri,20 May 2022 07:10:46 GMT 
 server: uvicorn 
 x-amzn-trace-id: Root=1-62873efa-529979dc1db26af3e616be67 
```

**Server log:**
```
cannot find the current segment/subsegment, please make sure you have a segment open
No segment found, cannot begin subsegment placekitten.com.
cannot find the current segment/subsegment, please make sure you have a segment open
cannot find the current segment/subsegment, please make sure you have a segment open
No segment found, cannot begin subsegment postgres.
cannot find the current segment/subsegment, please make sure you have a segment open
No segment found, cannot begin subsegment execute.
cannot find the current segment/subsegment, please make sure you have a segment open
2022-05-20 07:10:53,650 [uvicorn.access] [INFO] 172.27.0.1:62726 - "GET /test HTTP/1.1" 200
```

**In X-Ray:**
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/98422651/169473400-41b178b5-a4d4-44be-8dd1-90c121410553.png">

**Comment by garyd203** [comment] 2022-05-20 10:58
Hey @sean-a-grant , that screenshot from the X-Ray console is about what I would expect to see - there's a single top-level segment that takes a bit more than `1+1+0.5` seconds. That sounds better than your initial comment, which sounded like the top-level segment was completely incorrect.

This means that you have got the initial setup for `xraysink` and `aws_xray_sdk` correct. The middleware is intercepting calls and creating a segment. Well done ✅ 

If I can read between the lines a bit, what I think you're asking is:

1. Why are there logging messages for `cannot find the current segment/subsegment` and `No segment found`?
2. Why aren't there subsegments for the database call, inner function calls to `do_work` and `more_work`, and the external HTTP request?

The log messages are a symptom of xray-instrumented functions being called outside of a request handler. Unfortunately the `aws_xray_sdk` gives useless error messages in this case, but setting `RUNTIME_ERROR` will help you figure out what those function calls are and where they're being called from.

Note that internal function calls are not instrumented by default. If you want this, decorate them with `@in_subsegment` or `in_subsegment_async` from the `aws-xray_sdk` library - and then make sure you only call them inside a request handler!

However, database and external HTTP calls not showing up in the segment sounds more problematic. In this case, those two libraries should be instrumented by your `patch_all` call, so we would expect to see their use appear in the X-Ray console. I think in this case the fact that you also get the "no segment present" error messages is probably a separate symptom of the same problem...

Fundamentally, X-Ray instrumentation is about taking a piece of data from the incoming request (the trace id), and making sure that same piece of data is attached to any outgoing requests. This is done by using thread context for non-async code, or asyncio context for async code. But I suspect what is happening in your case is the following:

1. FastAPI is an *async* framework and handles an incoming request, which is passed to the *async* `xray_middleware`, which attaches the trace ID to the *async* context
2. FastAPI creates a separate thread pool to execute your *non-async* `test()` handler. The trace ID is not propagated from the *async* context into the *thread* context.
3. The `test()` handler calls `requests.get` and `engine.execute`, which are unable to find the trace ID on the thread context. Hence they log a message, and you don't get the segment information.

Hopefully I explained that clearly. If you're super-keen then a bit of time with a debugger should confirm that `test` is being executed in a different thread to `xray_middleware` (and possibly not in a direct function call stack).

Assuming this understanding is correct, I can see there's two ways forward for you:

1. The easy way: Make your handlers (and their downstream libraries for database and HTTP) be async. This is what I do, which is presumably why I've never encountered your situation.
2. The hard way: Write your own variation of `AsyncContext` that propagates the trace ID from the asyncio context into the thread context. This is probably going to be specific to FastAPI's particular mechanism for using that thread pool.

**Comment by sean-a-grant** [comment] 2022-05-25 06:40
@garyd203 Hi Gary and whoever else may be reading. I am glad to hear my implementation is correct. You're right on the money with your assumptions. Unfortunately my codebase does not use async due to the main thread becoming blocked under load.

https://fastapi.tiangolo.com/async/#path-operation-functions
> When you declare a path operation function with normal def instead of async def, it is run in an external threadpool that is then awaited, instead of being called directly (as it would block the server).

I tested it with async and it worked perfectly. 

Here is the full stack trace:
```
Traceback (most recent call last):
  File "/app/api.py", line 78, in catch_exceptions
    return await call_next(request)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 219, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 154, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.8/dist-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/controllers/work.py", line 49, in do_work
 ...
  File "/usr/local/lib/python3.8/dist-packages/aws_xray_sdk/ext/requests/patch.py", line 38, in _inject_header
    inject_trace_header(headers, xray_recorder.current_subsegment())
  File "/usr/local/lib/python3.8/dist-packages/aws_xray_sdk/core/recorder.py", line 315, in current_subsegment
    entity = self.get_trace_entity()
  File "/usr/local/lib/python3.8/dist-packages/aws_xray_sdk/core/recorder.py", line 390, in get_trace_entity
    return self.context.get_trace_entity()
  File "/usr/local/lib/python3.8/dist-packages/aws_xray_sdk/core/context.py", line 99, in get_trace_entity
    return self.handle_context_missing()
  File "/usr/local/lib/python3.8/dist-packages/aws_xray_sdk/core/context.py", line 123, in handle_context_missing
    raise SegmentNotFoundException(MISSING_SEGMENT_MSG)
```

I will attempt a solution the hard way and report back here, hopefully make a PR or share my solution for others. Thanks for the help!

**Comment by sean-a-grant** [comment] 2022-05-25 07:17
This seems to be the root of the issue: https://github.com/tiangolo/fastapi/issues/953

**Comment by garyd203** [comment] 2022-05-25 11:43
Thanks for digging into that @sean-a-grant . It's good to know we've bitten off a simple issue, isn't it :-)

**Comment by garyd203** [comment] 2022-05-25 11:53
Are you still thinking of attempting an implementation?

Tiangolo's [comment](https://github.com/tiangolo/fastapi/issues/953#issuecomment-586006249) seems helpful, although in our case the context var isn't expected to be modified inside the sync code, so we don't need to worry about the mutate-a-dictionary-indirectly approach.

However, we do need to make sure that we set the correct sync thread-local variable, because this has to match up with what the core sync `Context` in the `aws_xray_sdk` library looks for, because this is used to instrument the outgoing network calls.

I don't have heaps of time in the next few weeks to look into it myself, but good luck and thank you! Drop me a note if you get stuck and want someone to talk things over with.

**Comment by garyd203** [comment] 2023-10-11 09:58
Closing since we know what the problem is, and have documented a detailed solution separately in #89

**Closed by garyd203** 2023-10-11 09:58 UTC
Labels: usage-question

**Comment by sean-a-grant-old** [comment] 2023-10-11 22:56
@garyd203 apologies for the lack of reply. I wasn't able to devote more time to this, but I'm still following in case it is supported in the future :) Thanks for the assist!

**Comment by garyd203** [comment] 2023-10-12 02:48
No worries @sean-a-grant-old , I haven't had time either! I was mainly just wanting to combine the tickets together, are you happy to follow #89 instead?

**Comment by sean-a-grant-old** [comment] 2023-10-12 23:24
Absolutely! Thanks. [This (ultimately abandoned) PR might be a good hint](https://github.com/encode/starlette/pull/1258) on how to fix it.
